
Conexao:
    usuario: 'root'
    host: 'localhost'
    dataBase: 'root'
    senha: 'password'
    porta: '3306'
    
    
Mensagens:
    argumentos:
        - ''
        - ' &3/horas &7ver'
        - ' &3/horas &7top'
        - ''
    argumentosAdm:
        - ''
        - ' &3/horas &7ver'
        - ' &3/horas &7top'
        - ' &3/horas &7add'
        - ' &3/horas &7remove'
        - ' &3/horas &7set'
        - ' &3/horas &7reset'
        - ''
    Horas_Ver: ' &6Tempo Jogado: &f%d% &6Dias &f%h% &6Horas e &f%m% &6Minutos'
        